services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: empresa
      RABBITMQ_DEFAULT_PASS: empresa123

  mysql-db1:
    image: mysql:8
    container_name: mysql-db1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ms_person_client
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-db2:
    image: mysql:8
    container_name: mysql-db2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ms_accounts_movements
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: dannyruxx/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - rabbitmq
      - mysql-db1

  ms-person-client:
    image: dannyruxx/ms-person-client:latest
    container_name: ms-person-client
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081
      APP_NAME: ms-person-client
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: empresa
      RABBITMQ_PASSWORD: empresa123
      DATASOURCE_URL: jdbc:mysql://mysql-db1:3306/ms_person_client
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: rootpassword
      DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_SERVER: http://eureka-server:8761/eureka/
    depends_on:
      - mysql-db1
      - eureka-server

  ms-accounts-movements:
    image: dannyruxx/ms-accounts-movements:latest
    container_name: ms-accounts-movements
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8082
      APP_NAME: ms-accounts-movements
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: empresa
      RABBITMQ_PASSWORD: empresa123
      DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/ms_accounts_movements
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: rootpassword
      DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_SERVER: http://eureka-server:8761/eureka/
    depends_on:
      - rabbitmq
      - mysql-db2
      - eureka-server

  gateway:
    image: dannyruxx/gateway:latest
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_SERVER: http://eureka-server:8761/eureka/
      MS_ACCOUNTS_NAME: lb://ms-accounts-movements
      MS_PERSON_NAME: lb://ms-person-client
    depends_on:
      - rabbitmq
      - mysql-db1
      - eureka-server
      - ms-person-client
      - ms-accounts-movements

networks:
  bank-network:
    driver: bridge
